# Generated by Django 5.1.4 on 2026-03-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
    ]
