# Generated by Django 5.1.4 on 2026-03-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarutina',
            name='ejercicio',
            field=models.ManyToManyField(to='rutinas.ejercicio'),
        ),
        migrations.DeleteModel(
            name='EjercicioAplicado',
        ),
    ]
