# Generated by Django 5.1.4 on 2026-03-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0002_alter_diarutina_ejercicio_delete_ejercicioaplicado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejercicio',
            old_name='video_url',
            new_name='url',
        ),
    ]
