# Generated by Django 5.1.4 on 2026-03-28 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0003_rename_video_url_ejercicio_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarutina',
            name='ejercicio',
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(blank=True, null=True)),
                ('repeticiones', models.IntegerField(blank=True, null=True)),
                ('series', models.IntegerField(blank=True, null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.diarutina')),
            ],
        ),
    ]
