# Generated by Django 5.1.4 on 2026-03-28 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0004_remove_diarutina_ejercicio_rutinaejercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='rutinas.diarutina'),
        ),
    ]
