# Generated by Django 5.1.4 on 2026-03-29 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0005_alter_rutinaejercicio_rutina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarutina',
            options={'ordering': ['mes', 'dia'], 'verbose_name': 'Día de Rutina', 'verbose_name_plural': 'Días de Rutina'},
        ),
        migrations.AlterModelOptions(
            name='ejercicio',
            options={'verbose_name': 'Ejercicio', 'verbose_name_plural': 'Ejercicios'},
        ),
        migrations.AlterModelOptions(
            name='rutinaejercicio',
            options={'verbose_name': 'Ejercicio en Rutina', 'verbose_name_plural': 'Ejercicios en Rutina'},
        ),
        migrations.AlterField(
            model_name='diarutina',
            name='dia',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='diarutina',
            unique_together={('usuario', 'mes', 'dia')},
        ),
        migrations.AlterUniqueTogether(
            name='ejercicio',
            unique_together={('nombre', 'musculo')},
        ),
    ]
