# Generated by Django 5.1.4 on 2026-04-04 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0006_alter_diarutina_options_alter_ejercicio_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rutinaejercicio',
            unique_together={('rutina', 'ejercicio')},
        ),
    ]
